//! Phase 3A one-off validation: do the real labels generated by
//! `scripts/generate_real_labels.py` actually land in the same coordinate
//! system as `propose_one_step`'s candidate output? Not a permanent test --
//! a throwaway check run once during the ground-truth audit, kept here for
//! reproducibility. Usage:
//!   cargo run --release --example label_spotcheck

use renkin::candidate::{ProposalConfig, propose_one_step};
use renkin::chem_env::load_rules_from_file;
use std::collections::BTreeSet;
use std::fs;

fn main() {
    let rules = load_rules_from_file("data/templates_extracted_500.smi");
    println!("loaded {} rules", rules.len());

    let labels_path = "data/reranker_labels_uspto50k_test.jsonl";
    let content = fs::read_to_string(labels_path).expect("read labels");
    let sample: Vec<serde_json::Value> = content
        .lines()
        .take(40)
        .map(|l| serde_json::from_str(l).unwrap())
        .collect();

    let mut n_checked = 0;
    let mut n_any_candidate_match = 0;
    let mut n_zero_candidates = 0;

    for row in &sample {
        let target_id = row["target_id"].as_str().unwrap();
        let target_smiles = target_id_to_smiles(target_id);
        let correct_sets: Vec<BTreeSet<String>> = row["correct_precursor_sets"]
            .as_array()
            .unwrap()
            .iter()
            .map(|s| {
                s.as_array()
                    .unwrap()
                    .iter()
                    .map(|v| v.as_str().unwrap().to_string())
                    .collect()
            })
            .collect();

        let config = ProposalConfig::default();
        let pool = match propose_one_step(target_id, &target_smiles, &rules, &config) {
            Ok(p) => p,
            Err(e) => {
                println!("{target_id}: propose_one_step ERROR: {e}");
                continue;
            }
        };
        n_checked += 1;
        if pool.candidates.is_empty() {
            n_zero_candidates += 1;
        }
        let matched = pool.candidates.iter().any(|c| {
            let cset: BTreeSet<String> = c.precursor_smiles.iter().cloned().collect();
            correct_sets.contains(&cset)
        });
        if matched {
            n_any_candidate_match += 1;
        }
        println!(
            "{target_id}: {} candidates, ground_truth_reachable={}",
            pool.candidates.len(),
            matched
        );
    }

    println!(
        "\nsummary: checked={n_checked} zero_candidates={n_zero_candidates} \
         ground_truth_reachable={n_any_candidate_match}/{n_checked}"
    );
}

/// `sample_full_sorted.jsonl` target_id -> canonical_smiles lookup (small
/// enough to just re-read the file rather than re-plumb the sample loader).
fn target_id_to_smiles(target_id: &str) -> String {
    let content =
        fs::read_to_string("data/comparison/sample_full_sorted.jsonl").expect("read samples");
    for line in content.lines() {
        let v: serde_json::Value = serde_json::from_str(line).unwrap();
        if v["target_id"].as_str().unwrap() == target_id {
            return v["canonical_smiles"].as_str().unwrap().to_string();
        }
    }
    panic!("target_id {target_id} not found in sample_full_sorted.jsonl");
}
