#!/usr/bin/env python3
"""
Phase A.5 (candidate-generation coverage program): per-arm metrics for the
template-count scaling diagnosis. Given a one-step candidate pool already
generated by `renkin-pool-gen` at some template-set size, computes:

    zero_positive_rate (primary decision metric), positive_present_rate,
    ground_truth_precursor_recall (target-level, multi-route aware),
    dedup_rate (from source_template_count), plus whatever renkin-pool-gen's
    own stdout summary already reports (candidate cardinality percentiles,
    wall-clock latency, parse/zero-candidate/target-id-mismatch counts) --
    NOT re-derived here, just passed through into the same output file.

No route search, no reranker, no ranking/top1 -- candidate-pool coverage
only, per the Phase A.5 scope (see
data/phase_a5_template_scaling/findings.md once written).

Reuses scripts/train_reranker.py's functions (imported as a module, never
reimplemented) for pool/label loading and group-level coverage -- same
pattern as scripts/chemical_space_coverage_export_test_labels.py (Phase A).

Usage:
    python3 scripts/phase_a5_pool_metrics.py \
        --pool <pool.jsonl> --groups <groups.jsonl> \
        --labels data/reranker_labels_uspto50k_val.jsonl \
        --pool-gen-summary <captured renkin-pool-gen stdout JSON> \
        --arm-label 500 \
        --output <metrics.json>
"""
import argparse
import importlib.util
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

spec = importlib.util.spec_from_file_location("train_reranker", ROOT / "scripts" / "train_reranker.py")
tr = importlib.util.module_from_spec(spec)
spec.loader.exec_module(tr)


def dedup_rate(pool_rows):
    """1 - (unique merged candidates / raw pre-merge template-application
    successes). Each pool row is already a merged `ReactionCandidate`
    (candidate.rs's `merge_into_candidates` runs inside `propose_one_step`
    before rows are ever written) -- `source_template_count` on each row is
    how many raw per-template proposals collapsed into that one row, so
    summing it reconstructs the pre-merge count without needing any new
    RENKIN-side instrumentation.
    """
    if not pool_rows:
        return None
    raw_total = sum(r["source_template_count"] for r in pool_rows)
    merged_total = len(pool_rows)
    if raw_total == 0:
        return None
    return 1.0 - (merged_total / raw_total)


def ground_truth_precursor_recall(pool_rows, labels, group_records):
    """Target-level (not group-level): for each distinct target_id, the
    fraction of its own distinct correct_precursor_sets (pooled across all
    of that target's group_ids -- a target can have >1 historical route,
    hence >1 group_id in VAL/TRAIN's per-reaction group schema) that appear
    as a precursor set among ANY of that target's candidate rows.

    Differs from positive_present_rate (group-level: >=1 of the group's own
    correct sets found) only for the rare multi-route targets -- see
    findings.md for how many that was in practice. `labels` is
    train_reranker.py's own `load_labels()` output (group_id -> GroupLabel,
    `correct_precursor_sets` already a frozenset of sorted tuples) --
    reused as-is, not re-parsed, so matching stays consistent with every
    other coverage computation in this pipeline.
    """
    target_to_groups = {}
    for r in group_records:
        target_to_groups.setdefault(r["target_id"], []).append(r["group_id"])

    candidates_by_target = {}
    for row in pool_rows:
        candidates_by_target.setdefault(row["target_id"], set()).add(tuple(sorted(row["precursor_smiles"])))

    per_target_recall = []
    for target_id, group_ids in target_to_groups.items():
        true_sets = set()
        for gid in group_ids:
            label = labels.get(gid)
            if label is None:
                continue
            true_sets.update(label.correct_precursor_sets)
        if not true_sets:
            continue
        found = candidates_by_target.get(target_id, set())
        n_recovered = sum(1 for s in true_sets if s in found)
        per_target_recall.append(n_recovered / len(true_sets))

    if not per_target_recall:
        return None
    return sum(per_target_recall) / len(per_target_recall)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--pool", required=True)
    ap.add_argument("--groups", required=True)
    ap.add_argument("--labels", required=True)
    ap.add_argument("--pool-gen-summary", required=True, help="renkin-pool-gen's own stdout JSON, captured to a file")
    ap.add_argument("--arm-label", required=True)
    ap.add_argument("--output", required=True)
    args = ap.parse_args()

    pool_rows = tr.load_jsonl(args.pool)
    group_records = tr.load_jsonl(args.groups)
    labels = tr.load_labels(args.labels)

    tr.configure_split_override({r["target_id"]: "val" for r in group_records})

    labeled, unlabeled_count = tr.label_and_split_rows(pool_rows, labels, group_records, allow_unlabeled=False)
    val_rows = [r for r in labeled if r.split == "val"]
    coverage = tr.summarize_coverage(val_rows, group_records, labels, "val")

    pool_gen_summary = json.loads(Path(args.pool_gen_summary).read_text())

    result = {
        "arm_label": args.arm_label,
        "unlabeled_groups_excluded": unlabeled_count,
        "group_count": coverage.group_count,
        "target_count": coverage.target_count,
        "zero_positive_count": coverage.groups_with_zero_positive,
        "zero_positive_rate": coverage.groups_with_zero_positive / coverage.group_count if coverage.group_count else None,
        "positive_present_rate": 1 - (coverage.groups_with_zero_positive / coverage.group_count) if coverage.group_count else None,
        "ground_truth_precursor_recall_target_level": ground_truth_precursor_recall(pool_rows, labels, group_records),
        "dedup_rate": dedup_rate(pool_rows),
        "total_candidate_count": coverage.total_candidate_count,
        "positive_candidate_count": coverage.positive_candidate_count,
        "pool_gen_summary": pool_gen_summary,
    }

    Path(args.output).write_text(json.dumps(result, indent=2))
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
